ATTRIBUTE:
  USE_DISTRIBUTION_FILE:
    ENABLED: true
    FILE_PATH: data/attribute_distribution/output_options_list_camera_elev_msmt_1028_gamma_msmt_1027_merged.json
    LIMIT_FIELDS:
    - camera_elev
    - gamma_value
    RANDOM_SAMPLE:
      ENABLED: true
OUTPUT_DIR_FOR_ATTRIBUTE: data/dataset_MakeHuman/makehuman_2954_tagp_ta_msmt_20211117-a
OUTPUT_DIR_FOR_IMAGE: data/dataset_MakeHuman/makehuman_2954_tagp_ta_msmt_20211117
_BASE_: ../../TAGPerson_base.yml
