ATTRIBUTE:
  USE_DISTRIBUTION_FILE:
    ENABLED: true
    FILE_PATH: data/attribute_distribution/output_options_list_camera_elev_market_1028_gamma_market_1027_merged.json
    LIMIT_FIELDS:
    - camera_elev
    - gamma
    RANDOM_SAMPLE:
      ENABLED: true
OUTPUT_DIR_FOR_ATTRIBUTE: data/dataset_MakeHuman/makehuman_2954_tagp_ta_market_20211117-a
OUTPUT_DIR_FOR_IMAGE: data/dataset_MakeHuman/makehuman_2954_tagp_ta_market_20211117
_BASE_: ../../TAGPerson_base.yml
