ATTRIBUTE:
  USE_DISTRIBUTION_FILE:
    ENABLED: true
    FILE_PATH: data/attribute_distribution/output_options_list_camera_elev_grid_1028.json
    LIMIT_FIELDS:
    - camera_elev
    RANDOM_SAMPLE:
      ENABLED: true
OUTPUT_DIR_FOR_ATTRIBUTE: data/dataset_MakeHuman/makehuman_2954_tagp_tag_c_grid_20211117-a
OUTPUT_DIR_FOR_IMAGE: data/dataset_MakeHuman/makehuman_2954_tagp_tag_c_grid_20211117
_BASE_: ../../TAGPerson_base.yml
