_BASE_: '../base/base.yml'


RENDER:
  RESOLUTION_PERCENTAGE:
    BASE: 50
    RANDOM_LOWER_BOUND: 0
    RANDOM_UPPER_BOUND: 0
  RESOLUTION_X:
    BASE: 100
    RANDOM_UPPER_BOUND: 0
    RANDOM_LOWER_BOUND: 0
  RESOLUTION_Y:
    BASE: 256
    RANDOM_UPPER_BOUND: 0
    RANDOM_LOWER_BOUND: 0
  
CAMERA:
  ROTATION_EULER_X_BIAS:
    RANDOM:
      ENABLE: False
  ROTATION_EULER_Z_BIAS:
    RANDOM:
      ENABLE: False
  DISTANCE:
    RANDOM:
      LOWER_BOUND: 0.0
      UPPER_BOUND: 0.0
