OPTION:
  APPLY_CAMERA_WORLD_COLOR:
    ENABLE: false
OUTPUT_DIR_FOR_ATTRIBUTE: data/dataset_MakeHuman/makehuman_2954_tagp_no_wc-a
OUTPUT_DIR_FOR_IMAGE: data/dataset_MakeHuman/makehuman_2954_tagp_no_wc
_BASE_: ../TAGPerson_base.yml
